# Generated by Django 5.1.1 on 2024-09-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(default='-', max_length=7),
            preserve_default=False,
        ),
    ]
